name: README Workflow

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Generate Light Stats Card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: >
            {"username":"${{ github.repository_owner }}",
             "theme":"default",
             "hide_title":"true",
             "card_width":"495",
             "show_icons":"true",
             "rank_icon":"github"}
          path: profile/stats_light.svg
          token: ${{ secrets.PAT }}

      - name: Generate Dark Stats Card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: >
            {"username":"${{ github.repository_owner }}",
             "theme":"github_dark",
             "hide_title":"true",
             "card_width":"495",
             "show_icons":"true",
             "rank_icon":"github"}
          path: profile/stats_dark.svg
          token: ${{ secrets.PAT }}

      - name: Generate Light Wakatime Card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: wakatime
          options: >
            {"username":"ximon",
             "theme":"default",
             "hide_title":"true",
             "range":"last_7_days",
             "langs_count":"5"}
          path: profile/wakatime_light.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Dark Wakatime Card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: wakatime
          options: >
            {"username":"ximon",
             "theme":"github_dark",
             "hide_title":"true",
             "range":"last_7_days",
             "langs_count":"5"}
          path: profile/wakatime_dark.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update README cards" || exit 0
          git push
